baseURL: ''
languageCode: en-us
title: Kinvolk website
theme: kinvolk

menu:
  main:
    - name: Products
      url: /products
      identifier: products
      weight: -20
      icon: svg
    - name: Flatcar Linux
      parent: products
      title: Linux distribution for container workloads
      url: /
      weight: 1
      pre: <svg class="flatcar-logo" viewBox="0 0 66 40">
              <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/images/products/flatcar-logo.svg#flatcar-logo"></use>
            </svg>
    - name: Lokomotive
      parent: products
      title: Linux distribution for container workloads
      url: /
      weight: 1
      pre: <svg class="lokomotive-logo" viewBox="0 0 942 354">
              <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/images/products/lokomotive-logo.svg#lokomotive-logo"></use>
            </svg>

    - name: Services
      url: /services
      weight: -15
      icon: svg
    - name: Company
      url: /company
      identifier: company
      weight: -10
      icon: svg
    - name: Case Studies
      url: /case-studies
      weight: -5
    - name: Blog
      url: /blog
      weight: 0

params:
  footer:
    navlist:
      - title: Solutions
        quicklinks:
          - text: Kinvolk Monitor
            link: /
          - text: Kinvolk secure
            link: /
          - text: Kinvolk platform
            link: /
          - text: OpenSource
            link: /
          - text: Falco
            link: /
          - text: Use Cases
            link: /
          - text: Pricing
            link: /
          - text: Partners
            link: /
      - title: Support
        quicklinks:
          - text: Support Center
            link: /
          - text: Support Log-In
            link: /
          - text: Submit Ticket
            link: /
          - text: Kinvolk status
            link: /
          - text: Webinars 
            link: /
          - text: Newsletters
            link: /
          - text: Resources
            link: /
          - text: Docs
            link: /
      - title: Company
        quicklinks:
          - text: Blog
            link: /
          - text: About Us
            link: /
          - text: Press Kit
            link: /
          - text: In The News
            link: /
          - text: Press Releases
            link: /
          - text: Contact 
            link: /
          - text: Job
            link: /
  social:
  - title: Facebook
    url: 'https://www.facebook.com/kinvolk'
    image: "facebook-icon"
  - title: Twitter
    url: 'https://twitter.com/kinvolkio'
    image: 'twitter-icon'
  - title: Youtube
    url: 'https://www.youtube.com/channel/UCfUyOoIxN2vBVegHfkkegdA'
    image: 'youtube-icon'
  - title: Linkedin
    url: 'https://www.linkedin.com/company/kinvolk'
    image: 'linkedin-icon'
  - title: Github
    url: 'https://github.com/kinvolk'
    image: 'github-icon'