baseURL: '/'
languageCode: en-us
title: Cloud Native Rejekts
theme: rejekts

params:
  social:
  - title: Twitter
    url: 'https://twitter.com/rejektsio'
    image: 'twitter-icon'
  - title: Instagram
    url: 'https://www.instagram.com/Rejektsio/'
    image: 'instagram-icon'
