baseURL = "/"
languageCode = "en-us"
title = "The Kinwolk website"
theme = "kinvolk"

[params]

[params.footer]
  [[params.footer.navlist]]
    title = "Products"
    [[params.footer.navlist.quicklinks]]
        text = "Lokomotive"
        link = "/products/lokomotive"
    [[params.footer.navlist.quicklinks]]
        text = "Flatcar Linux"
        link = "/products/flatcar-linux"
  [[params.footer.navlist]]
    title = "Services"
    [[params.footer.navlist.quicklinks]]
        text = "Engineering"
        link = "/services/engineering"
    [[params.footer.navlist.quicklinks]]
        text = "Penetration testing"
        link = "/services/penetration-testing"
    [[params.footer.navlist.quicklinks]]
        text = "Training"
        link = "/services/training"
  [[params.footer.navlist]]
    title = "Company"
    [[params.footer.navlist.quicklinks]]
        text = "About"
        link = "/company/about"
    [[params.footer.navlist.quicklinks]]
        text = "Careers"
        link = "/company/careers"
    [[params.footer.navlist.quicklinks]]
        text = "Imprint"
        link = "/company/imprint"

  [[params.social]]
    title = "github"
    url = "https://github.com/kinvolk"
  [[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/kinvolk"
  [[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/company/kinvolk"
  [[params.social]]
    title = "twitter"
    url = "https://twitter.com/kinvolkio"



[[menu.main]]
    name = "Products"
    url = "/products"
    identifier = "products"
    weight = -160

[[menu.main]]
    name = "Services"
    url = "/services"
    weight = -170

[[menu.main]]
    name = "Company"
    url = "/company"
    weight = -175

[[menu.main]]
    name = "Case Studies"
    url = "/case-studies"
    weight = -180

[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = -185
 